# Endpoints
endpoints:
  restart:
    enabled: true
    
#Feign
feign:
  client:
    config:
      default:
        connectTimeout: 150000
        loggerLevel: full
        readTimeout: 150000
  compression:
    request:
      mime-types: "application/json"
      
# Integration
integration:
  user:
    baseUrl: ${info.client.userBaseUrl} 

# Server
server:
  port: ${info.application.port}
logging:
  level:
    br.com.nt.application.service.client: debug
    org.springframework.boot.autoconfigure: off 

# Spring
spring: 
  application:
    name: nt
  jackson:
    default-property-inclusion: non-null
    date-format: "yyyy-MM-dd"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: ${info.mysql.urlConection}

    
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        votacaoOutput:
          destination: nt-votacao
          group: group
          durableSubscription: true
          consumer:
            concurrency: 3
            maxAttempts: 5
            backOffInitialInterval: 30000
            backOffMaxInterval: 60000
            acknowledgeMode: AUTO
      binders:
        rabbit:
          type: rabbit
  rabbitmq:
    host: shark.rmq.cloudamqp.com 
    #port: 49388
    username: obwlpzqe
    password: aGNhvj7dkYtGz3vy2rzLqcVKe48hRf3R
    virtual-host: obwlpzqe