# Endpoints
endpoints:
  restart:
    enabled: true
    
#Feign
feign:
  client:
    config:
      default:
        connectTimeout: 150000
        loggerLevel: full
        readTimeout: 150000
  compression:
    request:
      mime-types: "application/json"
      
# Integration
integration:
  user:
    baseUrl: ${info.client.userBaseUrl} 

# Server
server:
  port: ${info.application.port}
logging:
  level:
    br.com.nt.application.service.client: debug
    org.springframework.boot.autoconfigure: off 

# Spring
spring: 
  application:
    name: nt
  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
#    url: ${info.mysql.urlConection}
#    username: ${info.mysql.user}
#    password: ${info.mysql.pwd}

#mysql://b10808a6ce7419:ef0750bb@us-cdbr-east-03.cleardb.com/heroku_8afbad2c1f5d6f2?reconnect=true
    url: 'jdbc:mysql://b10808a6ce7419:ef0750bb@us-cdbr-east-03.cleardb.com/heroku_8afbad2c1f5d6f2?reconnect=true'
#    username: b10808a6ce7419
#    password: 0b3f30109b95a6a 
    
#    mysql://b8ede2fd643c70:dc0858ed@ us-cdbr-east-02.cleardb.com/heroku_d10ed8bfae0e85f?reconnect=true
    
#    url: 'jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_b28b131411deef4?reconnect=true'
#    username: be1453100c9a18
#    password: b617cf96

#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false