# Endpoints
endpoints:
  restart:
    enabled: true
    
#Feign
feign:
  client:
    config:
      default:
        connectTimeout: 150000
        loggerLevel: full
        readTimeout: 150000
  compression:
    request:
      mime-types: "application/json"
      
# Integration
integration:
  user:
    baseUrl: ${info.client.userBaseUrl} 

# Server
server:
  port: ${info.application.port}
logging:
  level:
    br.com.nt.application.service.client: debug
    org.springframework.boot.autoconfigure: off 

# Spring
spring: 
  application:
    name: nt
  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: ${info.mysql.urlConection}
#    url: 'jdbc:mysql://b10808a6ce7419:0b3f30109b95a6a@us-cdbr-east-03.cleardb.com:3306/heroku_8afbad2c1f5d6f2?reconnect=true'
